# Generated by Django 5.0.7 on 2024-07-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_alter_employee_email_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
