# Generated by Django 5.0.7 on 2024-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_alter_employee_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
