# Generated by Django 5.0.7 on 2024-07-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_alter_employee_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='emailId',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
